#!/usr/bin/env bash
# Example /etc/portage/ebuild.postmerge.d script. Make it executable (chmod +x) for
# Portage to process it.
#
# ebuild.postmerge.d hooks are called when an individual package merge succeeds.
# The arguments are the package CPV and ROOT.

package_cpv=${1}
root_dir=${2}

echo "* In postmerge hook for ${package_cpv}"
echo "** ROOT: ${root_dir}"

# exit 0
